matrix:
    include:
        - language: python
          cache: pip
          python: "3.8.1"
          install:
            - pip install pipenv --upgrade
            - pipenv sync -d
          before_script:
            - python --version
          script:
            - black --line-length 120 --check . backend/src/
            - flake8
            - pre-commit run --all-files
            - pytest
            - coverage erase
            - coverage run -m pytest && coverage html
          after_success:
            - bash <(curl -s https://codecov.io/bash)
