apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quizz-app
  name: quizz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizz-app
  template:
    metadata:
      labels:
        app: quizz-app
    spec:
      containers:
        - image: ericrommel/quizz-api-kb
          name: quizz-app
          ports:
          - containerPort: 5000
            name: http

---
apiVersion: v1
kind: Service
metadata:
  name: quizz-app
  labels:
    app: quizz-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: quizz-app
