"""empty message

Revision ID: 041652e9f19f
Revises:
Create Date: 2020-11-21 12:19:51.000192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "041652e9f19f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("correct_answer", sa.String(length=500), nullable=True),
        sa.Column("subject", sa.String(length=100), nullable=True),
        sa.Column("false_answer_1", sa.String(length=500), nullable=True),
        sa.Column("false_answer_2", sa.String(length=500), nullable=True),
        sa.Column("false_answer_3", sa.String(length=500), nullable=True),
        sa.Column("level", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_correct_answer"), "questions", ["correct_answer"], unique=False)
    op.create_index(op.f("ix_questions_description"), "questions", ["description"], unique=True)
    op.create_index(op.f("ix_questions_false_answer_1"), "questions", ["false_answer_1"], unique=False)
    op.create_index(op.f("ix_questions_false_answer_2"), "questions", ["false_answer_2"], unique=False)
    op.create_index(op.f("ix_questions_false_answer_3"), "questions", ["false_answer_3"], unique=False)
    op.create_index(op.f("ix_questions_level"), "questions", ["level"], unique=False)
    op.create_index(op.f("ix_questions_subject"), "questions", ["subject"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(length=120), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=80), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_fullname"), "users", ["fullname"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("questions", sa.PickleType(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "first_execution", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("next_execution", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quiz_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("quiz_id", sa.Integer(), nullable=True),
        sa.Column("time_for_execution", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=True),
        sa.Column("results", sa.PickleType(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores")
    op.drop_table("quiz_users")
    op.drop_table("quizzes")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_fullname"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_questions_subject"), table_name="questions")
    op.drop_index(op.f("ix_questions_level"), table_name="questions")
    op.drop_index(op.f("ix_questions_false_answer_3"), table_name="questions")
    op.drop_index(op.f("ix_questions_false_answer_2"), table_name="questions")
    op.drop_index(op.f("ix_questions_false_answer_1"), table_name="questions")
    op.drop_index(op.f("ix_questions_description"), table_name="questions")
    op.drop_index(op.f("ix_questions_correct_answer"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
