"""empty message

Revision ID: 377b189c13aa
Revises: bd87cf4114d0
Create Date: 2020-11-16 12:06:37.414261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "377b189c13aa"
down_revision = "bd87cf4114d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("level", sa.String(length=15), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_description"), "questions", ["description"], unique=False)
    op.create_index(op.f("ix_questions_level"), "questions", ["level"], unique=True)
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_answers_description"), "answers", ["description"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answers_description"), table_name="answers")
    op.drop_table("answers")
    op.drop_index(op.f("ix_questions_level"), table_name="questions")
    op.drop_index(op.f("ix_questions_description"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
