"""empty message

Revision ID: 5c09d3be8436
Revises: 377b189c13aa
Create Date: 2020-11-16 12:30:36.580078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c09d3be8436"
down_revision = "377b189c13aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_answers_description", table_name="answers")
    op.drop_table("answers")
    op.add_column("questions", sa.Column("correct_answer", sa.String(length=500), nullable=True))
    op.add_column("questions", sa.Column("false_answer_1", sa.String(length=500), nullable=True))
    op.add_column("questions", sa.Column("false_answer_2", sa.String(length=500), nullable=True))
    op.add_column("questions", sa.Column("false_answer_3", sa.String(length=500), nullable=True))
    op.create_index(op.f("ix_questions_correct_answer"), "questions", ["correct_answer"], unique=False)
    op.create_index(op.f("ix_questions_false_answer_1"), "questions", ["false_answer_1"], unique=False)
    op.create_index(op.f("ix_questions_false_answer_2"), "questions", ["false_answer_2"], unique=False)
    op.create_index(op.f("ix_questions_false_answer_3"), "questions", ["false_answer_3"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_false_answer_3"), table_name="questions")
    op.drop_index(op.f("ix_questions_false_answer_2"), table_name="questions")
    op.drop_index(op.f("ix_questions_false_answer_1"), table_name="questions")
    op.drop_index(op.f("ix_questions_correct_answer"), table_name="questions")
    op.drop_column("questions", "false_answer_3")
    op.drop_column("questions", "false_answer_2")
    op.drop_column("questions", "false_answer_1")
    op.drop_column("questions", "correct_answer")
    op.create_table(
        "answers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("description", sa.VARCHAR(length=500), nullable=True),
        sa.Column("is_correct", sa.BOOLEAN(), nullable=True),
        sa.Column("question_id", sa.INTEGER(), nullable=True),
        sa.CheckConstraint("is_correct IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_answers_description", "answers", ["description"], unique=False)
    # ### end Alembic commands ###
