"""empty message

Revision ID: 95008fb9e263
Revises: 5c09d3be8436
Create Date: 2020-11-16 13:01:35.744077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95008fb9e263"
down_revision = "5c09d3be8436"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("subject", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_questions_subject"), "questions", ["subject"], unique=False)
    op.drop_index("ix_questions_level", table_name="questions")
    op.create_index(op.f("ix_questions_level"), "questions", ["level"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_level"), table_name="questions")
    op.create_index("ix_questions_level", "questions", ["level"], unique=1)
    op.drop_index(op.f("ix_questions_subject"), table_name="questions")
    op.drop_column("questions", "subject")
    # ### end Alembic commands ###
